Replace 'keras' import by 'tensorflow.keras'
As mentionned in the StackOverflow response below, 'keras' and
'tensorflow.keras' are 2 different modules. Hence, there was an error
raising ("ImportError: cannot import name 'adam' from
'keras.optimizers").

https://stackoverflow.com/questions/62707558/importerror-cannot-import-name-adam-from-keras-optimizers